### ISSUE TITLE
navbar do projeto todo

### ISSUE THREAD

**Issue by VictorArnaud** [VictorArnaud/website#13]
## Navbar

- [x] Responsivo
- [x] Fixo
- [x] Logo lado esquerdo do navbar (Por enquanto Victor Arnaud)
- [x] URL de admin será: /admin/
- [x] Links em tabs com todas as funcionalidade citadas na descrição
- [x] Ao clicar no link do navbar será redirecionado a alguma parte do página home
- [ ] Testar
- [ ] Traduzir
